package ventas.computers.igu;

import java.awt.Color;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;

import javax.swing.BorderFactory;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventas.computers.impresion.Imprimir;
import ventas.computers.logica.ControladoraLogica;
import ventas.computers.logica.Productos;

public class PANEL_HOME extends javax.swing.JFrame {

    static List<Object[]> datos = new ArrayList<>();
    String producto_busqueda = "";
    LOGIN inicio = new LOGIN();

    static boolean busqueda = false;
    ControladoraLogica CL = new ControladoraLogica();

    public static Double PrecioFinal = 0.00;
    public static Double PagoFinal = 0.00;
    static int Count = 0;
    int unidades = 1;
    int Repetidor = 0;
    int identificador;

    public PANEL_HOME() {

        initComponents();

        /* Adjunta el usuario logiado y lo agrega 
        al texto de bienvenida */
        jtxt_user.setText(inicio.getUser() + " a Ventas Computer's");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REGISTRAR = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        txt_categoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        COMPRAS = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductosCompra = new javax.swing.JTable();
        btn_eliminarList = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        jlb_productosA = new javax.swing.JLabel();
        jbl_productosAPrice = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        TXT_PAGO = new javax.swing.JTextField();
        jbl_productosAPrice1 = new javax.swing.JLabel();
        jcb_online = new javax.swing.JCheckBox();
        jbl_productosAPrice2 = new javax.swing.JLabel();
        EDITAR = new javax.swing.JFrame();
        jpanelEditar = new javax.swing.JPanel();
        txt_Editar_nombre = new javax.swing.JTextField();
        jlb_Editar_nombre = new javax.swing.JLabel();
        txt_Editar_precio = new javax.swing.JTextField();
        jlb_Editar_precio = new javax.swing.JLabel();
        jlb_Editar_stock = new javax.swing.JLabel();
        txt_Editar_stock = new javax.swing.JTextField();
        txt_Editar_categoria = new javax.swing.JTextField();
        jlb_Editar_categoria = new javax.swing.JLabel();
        btn_Editar_editar = new javax.swing.JButton();
        btn_Editar_cerrar = new javax.swing.JButton();
        txt_Editar_codigo = new javax.swing.JTextField();
        jlb_Editar_codigo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxt_bienvenido = new javax.swing.JLabel();
        jtxt_user = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_producto = new javax.swing.JTextField();
        btn_busqueda = new javax.swing.JButton();
        jlb_intruccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btn_cambiar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        AgregarCompra = new javax.swing.JButton();
        jlb_productosAgregados = new javax.swing.JLabel();
        jlb_unidades = new javax.swing.JLabel();
        txt_unidades = new javax.swing.JTextField();

        REGISTRAR.setTitle("REGISTRAR PRODUCTO");
        REGISTRAR.setLocationByPlatform(true);
        REGISTRAR.setUndecorated(true);
        REGISTRAR.setResizable(false);
        REGISTRAR.setSize(new java.awt.Dimension(446, 396));

        jPanel4.setBackground(java.awt.Color.darkGray);
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRECIO");

        jLabel4.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STOCK");

        jLabel5.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CATEGORIA");

        btn_3.setBackground(new java.awt.Color(102, 255, 153));
        btn_3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/agregar.png"))); // NOI18N
        btn_3.setText("REGISTRAR");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/cerrar.png"))); // NOI18N
        jButton2.setText("CERRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CODIGO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout REGISTRARLayout = new javax.swing.GroupLayout(REGISTRAR.getContentPane());
        REGISTRAR.getContentPane().setLayout(REGISTRARLayout);
        REGISTRARLayout.setHorizontalGroup(
            REGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        REGISTRARLayout.setVerticalGroup(
            REGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        COMPRAS.setTitle("REGISTRAR PRODUCTO");
        COMPRAS.setLocationByPlatform(true);
        COMPRAS.setUndecorated(true);
        COMPRAS.setResizable(false);
        COMPRAS.setSize(new java.awt.Dimension(492, 525));
        COMPRAS.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                COMPRASWindowActivated(evt);
            }
        });

        jPanel5.setBackground(java.awt.Color.darkGray);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablaProductosCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        { @Override public boolean isCellEditable(int row, int column) { // Aquí puedes definir la lógica para determinar si una celda es editable // Por ejemplo, hacer que solo la primera columna sea editable
            return column == 0; } }
    );
    TablaProductosCompra.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane2.setViewportView(TablaProductosCompra);

    btn_eliminarList.setBackground(new java.awt.Color(255, 51, 51));
    btn_eliminarList.setText("ELIMINAR");
    btn_eliminarList.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_eliminarListActionPerformed(evt);
        }
    });

    btn_cerrar.setBackground(new java.awt.Color(255, 0, 0));
    btn_cerrar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_cerrar.setText("CERRAR");
    btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_cerrarActionPerformed(evt);
        }
    });

    jlb_productosA.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jlb_productosA.setForeground(new java.awt.Color(0, 255, 0));
    jlb_productosA.setText("dsadasdasasdasdasdas");

    jbl_productosAPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jbl_productosAPrice.setForeground(new java.awt.Color(0, 255, 0));
    jbl_productosAPrice.setText("asdasdasdasdasdasdasd");

    btn_ok.setBackground(new java.awt.Color(51, 255, 51));
    btn_ok.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_ok.setText("CONFIRMAR");
    btn_ok.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_okActionPerformed(evt);
        }
    });

    TXT_PAGO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    TXT_PAGO.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TXT_PAGOActionPerformed(evt);
        }
    });

    jbl_productosAPrice1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jbl_productosAPrice1.setForeground(new java.awt.Color(0, 255, 0));
    jbl_productosAPrice1.setText("Pago online");

    jcb_online.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jcb_onlineActionPerformed(evt);
        }
    });

    jbl_productosAPrice2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jbl_productosAPrice2.setForeground(new java.awt.Color(0, 255, 0));
    jbl_productosAPrice2.setText("PÁGO CON:");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbl_productosAPrice1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jcb_online))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jbl_productosAPrice2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(btn_eliminarList, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TXT_PAGO, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlb_productosA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbl_productosAPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(119, 119, 119))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btn_eliminarList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jlb_productosA, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jbl_productosAPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXT_PAGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbl_productosAPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcb_online, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbl_productosAPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    javax.swing.GroupLayout COMPRASLayout = new javax.swing.GroupLayout(COMPRAS.getContentPane());
    COMPRAS.getContentPane().setLayout(COMPRASLayout);
    COMPRASLayout.setHorizontalGroup(
        COMPRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(COMPRASLayout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, 0))
    );
    COMPRASLayout.setVerticalGroup(
        COMPRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(COMPRASLayout.createSequentialGroup()
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, 0))
    );

    EDITAR.setUndecorated(true);
    EDITAR.setResizable(false);
    EDITAR.setSize(new java.awt.Dimension(433, 398));
    EDITAR.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosed(java.awt.event.WindowEvent evt) {
            EDITARWindowClosed(evt);
        }
        public void windowOpened(java.awt.event.WindowEvent evt) {
            EDITARWindowOpened(evt);
        }
    });

    jpanelEditar.setBackground(java.awt.Color.darkGray);
    jpanelEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jpanelEditar.setMinimumSize(new java.awt.Dimension(428, 368));

    txt_Editar_nombre.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_Editar_nombreActionPerformed(evt);
        }
    });

    jlb_Editar_nombre.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
    jlb_Editar_nombre.setForeground(new java.awt.Color(255, 255, 255));
    jlb_Editar_nombre.setText("NOMBRE");

    jlb_Editar_precio.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
    jlb_Editar_precio.setForeground(new java.awt.Color(255, 255, 255));
    jlb_Editar_precio.setText("PRECIO");

    jlb_Editar_stock.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
    jlb_Editar_stock.setForeground(new java.awt.Color(255, 255, 255));
    jlb_Editar_stock.setText("STOCK");

    jlb_Editar_categoria.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
    jlb_Editar_categoria.setForeground(new java.awt.Color(255, 255, 255));
    jlb_Editar_categoria.setText("CATEGORIA");

    btn_Editar_editar.setBackground(new java.awt.Color(255, 255, 51));
    btn_Editar_editar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_Editar_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/editar.png"))); // NOI18N
    btn_Editar_editar.setText("EDITAR");
    btn_Editar_editar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_Editar_editarActionPerformed(evt);
        }
    });

    btn_Editar_cerrar.setBackground(new java.awt.Color(255, 102, 102));
    btn_Editar_cerrar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_Editar_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/cerrar.png"))); // NOI18N
    btn_Editar_cerrar.setText("CERRAR");
    btn_Editar_cerrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_Editar_cerrarActionPerformed(evt);
        }
    });

    jlb_Editar_codigo.setFont(new java.awt.Font("Sitka Display", 0, 16)); // NOI18N
    jlb_Editar_codigo.setForeground(new java.awt.Color(255, 255, 255));
    jlb_Editar_codigo.setText("CODIGO");

    javax.swing.GroupLayout jpanelEditarLayout = new javax.swing.GroupLayout(jpanelEditar);
    jpanelEditar.setLayout(jpanelEditarLayout);
    jpanelEditarLayout.setHorizontalGroup(
        jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEditarLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jlb_Editar_categoria)
                .addComponent(jlb_Editar_nombre)
                .addComponent(jlb_Editar_stock)
                .addComponent(jlb_Editar_precio)
                .addComponent(jlb_Editar_codigo))
            .addGap(18, 18, 18)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(txt_Editar_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_Editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_Editar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_Editar_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_Editar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(76, 76, 76))
        .addGroup(jpanelEditarLayout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addComponent(btn_Editar_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Editar_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40))
    );
    jpanelEditarLayout.setVerticalGroup(
        jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jpanelEditarLayout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_Editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlb_Editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlb_Editar_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_Editar_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_Editar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlb_Editar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_Editar_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlb_Editar_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_Editar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlb_Editar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addGroup(jpanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btn_Editar_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Editar_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(15, 15, 15))
    );

    javax.swing.GroupLayout EDITARLayout = new javax.swing.GroupLayout(EDITAR.getContentPane());
    EDITAR.getContentPane().setLayout(EDITARLayout);
    EDITARLayout.setHorizontalGroup(
        EDITARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EDITARLayout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jpanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, 0))
    );
    EDITARLayout.setVerticalGroup(
        EDITARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(EDITARLayout.createSequentialGroup()
            .addComponent(jpanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("VENTAS COMPUTER'S");
    setUndecorated(true);
    setSize(new java.awt.Dimension(486, 374));
    addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
        }
    });

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jPanel2.setBackground(java.awt.Color.darkGray);

    jtxt_bienvenido.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
    jtxt_bienvenido.setForeground(new java.awt.Color(255, 255, 255));
    jtxt_bienvenido.setText("Bienvenido");

    jtxt_user.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
    jtxt_user.setForeground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtxt_bienvenido)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jtxt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(37, 37, 37))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(41, 41, 41)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jtxt_bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(42, Short.MAX_VALUE))
    );

    jPanel3.setBackground(java.awt.Color.gray);

    btn_agregar.setBackground(new java.awt.Color(102, 255, 153));
    btn_agregar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/agregar.png"))); // NOI18N
    btn_agregar.setText("AGREGAR");
    btn_agregar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_agregarActionPerformed(evt);
        }
    });

    btn_editar.setBackground(new java.awt.Color(255, 255, 51));
    btn_editar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/editar.png"))); // NOI18N
    btn_editar.setText("EDITAR");
    btn_editar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_editarActionPerformed(evt);
        }
    });

    btn_eliminar.setBackground(new java.awt.Color(255, 0, 51));
    btn_eliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/borrar.png"))); // NOI18N
    btn_eliminar.setText("ELIMINAR");
    btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_eliminarActionPerformed(evt);
        }
    });

    jButton1.setBackground(java.awt.Color.cyan);
    jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/salir.png"))); // NOI18N
    jButton1.setText("CERRAR SESSION");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jButton1)))
            .addContainerGap(17, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(btn_agregar)
            .addGap(42, 42, 42)
            .addComponent(btn_editar)
            .addGap(42, 42, 42)
            .addComponent(btn_eliminar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1)
            .addContainerGap())
    );

    txt_producto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    txt_producto.setForeground(new java.awt.Color(204, 204, 204));
    txt_producto.setText("EJEMPLO: Ryzen 5");
    txt_producto.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txt_productoFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txt_productoFocusLost(evt);
        }
    });
    txt_producto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_productoActionPerformed(evt);
        }
    });

    btn_busqueda.setBackground(new java.awt.Color(0, 255, 204));
    btn_busqueda.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    btn_busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/busqueda.png"))); // NOI18N
    btn_busqueda.setText("BUSCAR");
    btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_busquedaActionPerformed(evt);
        }
    });

    jlb_intruccion.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
    jlb_intruccion.setForeground(new java.awt.Color(153, 153, 153));
    jlb_intruccion.setText("Introduce el nombre del producto");

    TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    TablaProductos.setFocusable(false);
    TablaProductos.setRequestFocusEnabled(false);
    TablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(TablaProductos);

    jButton3.setBackground(java.awt.Color.green);
    jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/cobrar.png"))); // NOI18N
    jButton3.setText("COBRAR");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    btn_cambiar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    btn_cambiar.setForeground(new java.awt.Color(0, 102, 255));
    btn_cambiar.setText("CAMBIAR A BUSQUEDA POR CODIGO");
    btn_cambiar.setOpaque(false); // Hace que el JTextField sea transparente
    btn_cambiar.setBackground(new Color(0, 0, 0, 0)); // Establece el fondo del JTextField como transparente
    btn_cambiar.setBorder(BorderFactory.createEmptyBorder()); // Elimina el borde del JTextField
    btn_cambiar.setBorder(null);
    btn_cambiar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_cambiarActionPerformed(evt);
        }
    });

    jButton4.setBackground(new java.awt.Color(102, 255, 102));
    jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/actualizar.png"))); // NOI18N
    jButton4.setText("Actualizar");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    AgregarCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    AgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas/computers/resource/compra.png"))); // NOI18N
    AgregarCompra.setText("Agregar Compra");
    AgregarCompra.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AgregarCompraActionPerformed(evt);
        }
    });

    jlb_productosAgregados.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N

    jlb_unidades.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
    jlb_unidades.setText("UNIDADES");

    txt_unidades.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
    txt_unidades.setText("1");
    txt_unidades.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            txt_unidadesMouseClicked(evt);
        }
    });
    txt_unidades.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_unidadesActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_intruccion)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                            .addComponent(btn_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cambiar)))
                    .addGap(28, 28, 28))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlb_unidades))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AgregarCompra)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_productosAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27))))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(btn_cambiar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_intruccion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jlb_productosAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AgregarCompra)
                                        .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jlb_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15))))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, 0))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txt_productoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_productoFocusGained
        txt_producto.setText(producto_busqueda);
        txt_producto.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_productoFocusGained

    private void txt_productoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_productoFocusLost

        producto_busqueda = txt_producto.getText();
    }//GEN-LAST:event_txt_productoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        inicio.setVisible(true);
        inicio.setLocationRelativeTo(this);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed

        try {

            DefaultTableModel TablaDefault = new DefaultTableModel() {
            };

            // nombres de columnas
            String titulos[] = {"CODIGO", "NOMBRE", "STOCK", "PRECIO", "CATEGORIA", "ID"};

            //Setear nombres en coolumnas
            TablaDefault.setColumnIdentifiers(titulos);

// BUSCAR POR NOMBRE O POR CODIGO 
// BUENA PRACTICA RESUMIENDO CODIGO
//*************************************************************
            List<Productos> listaproductos;

            if (busqueda == false) {
                listaproductos = CL.BuscarProductoNombre(txt_producto.getText().toUpperCase());
            } else {
                listaproductos = CL.BuscarProductoCodigo(Integer.parseInt(txt_producto.getText()));
            }
// ********************************************************

//recorrer la lista y mostrar elementos
            if (listaproductos != null) {
                for (Productos product : listaproductos) {
                    Object[] columnas = {product.getCodigo(), product.getNombre(),
                        product.getStock(), product.getPrecio(), product.getCategoria(), product.getId()};
//agregar listas 
                    TablaDefault.addRow(columnas);
                }
            }

            TablaProductos.setModel(TablaDefault);


            /* SI LAS CELDAS(Row) SON MENORES A 1 Y LA BUSQUEDA SE HACE EN NOMBRES
        QUE TIRE UN MENSSAGE DIALOG CORRESPONDIENTE
        SI ES CON CODIGO QUE TIRE OTRO*/
            if (TablaProductos.getRowCount() < 1) {

                if (busqueda == false) {
                    JOptionPane.showMessageDialog(rootPane, "No existe un producto con este Nombre");

                } else {
                    JOptionPane.showMessageDialog(rootPane, "No existe un producto con este Codigo");

                }
                ComprobarTextoDeBusqueda(busqueda);
                cargarTabla();

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Error en el codigo del producto");
            ComprobarTextoDeBusqueda(busqueda);
            cargarTabla();
        }


    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void txt_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productoActionPerformed


    }//GEN-LAST:event_txt_productoActionPerformed

    private void btn_cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiarActionPerformed
        CambiarTextoDeBusqueda();


    }//GEN-LAST:event_btn_cambiarActionPerformed


    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        /*    AGREGAR PRODUCTO Y DEJAR DESACTIVADO EL JFRAME DE ATRAS 
        ASI NO TOQUETEAN,BUGEAN O ABREN MILES DE AGREGAR PRODUCTO
         */
        this.setEnabled(false);

        REGISTRAR.setLocationRelativeTo(null);
        REGISTRAR.setVisible(true);
        //Cuando se vuelve a abrir este metodo limpia los campos
        LimpiarRegistrarP();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed

        //REGISTRO DE NUEVO PRODUCTO
        try {
            Productos product = new Productos(0, txt_nombre.getText(), Integer.parseInt(txt_stock.getText()), Double.parseDouble(txt_precio.getText()), txt_categoria.getText(), Integer.parseInt(txt_codigo.getText()));
            CL.crearProducto(product);
            JOptionPane.showMessageDialog(rootPane, "PRODUCTO REGISTRADO CORRECTAMENTE");
            //CERRAR EL REGISTRO PERO VOLVER A HABILITAR EL MENU PRINCIPAL(PANEL_HOME)
            this.setEnabled(true);
            REGISTRAR.dispose();
            cargarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR EN EL REGISTRO DEL PRODUCTO REVISA LOS DATOS");
        }


    }//GEN-LAST:event_btn_3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//CERRAR EL REGISTRO PERO VOLVER A HABILITAR EL MENU PRINCIPAL(PANEL_HOME)
        this.setEnabled(true);
        REGISTRAR.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*  Cuando se abra este Jfrom que se establescan estos valores 
 para evitar posibles errores */

        cargarTabla();
        PrecioFinal = 0.00;
        PagoFinal = 0.00;
        Count = 0;
        unidades = 1;


    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// Actualizar la tabla
        cargarTabla();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        /*  Si no hay nada selecionado en la tabla productos da un mensage de error
        para evitar errores y si si hay algo seleccionado que se abra y se cargue
        todos los txt_field 
         */ if (TablaProductos.getSelectedRow() != -1) {
            this.setEnabled(false);
            EDITAR.setLocationRelativeTo(null);
            EDITAR.setVisible(true);
            CargarEditar();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Porfavor seleccione un producto");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        /*Obtener valor deseado seleccionando la tabla
        en este caso la ID */
        int id = (int) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 5);

        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar este Producto?");
        if (opcion == JOptionPane.YES_OPTION) {

            try {

                CL.eliminar(id);
                cargarTabla();

                JOptionPane.showMessageDialog(rootPane, "Se a eliminado correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Se a cancelado la operación");
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void AgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCompraActionPerformed
        /*
        Manejar excepciones y traer datos de los productos seleccionados
        y agregarlos en los jlb_txt
         */
        try {
            Double Precio = (Double) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 3);
            unidades = Integer.parseInt(txt_unidades.getText());
            PrecioFinal = PrecioFinal + Precio * unidades;
            Count = Count + unidades;
            BigDecimal redondear = new BigDecimal(PrecioFinal);
            redondear = redondear.setScale(2, RoundingMode.UP);
            jlb_productosAgregados.setForeground(Color.GREEN);
            jlb_productosAgregados.setText("+ " + Count + " Precio Final: " + redondear);
            txt_unidades.setText("1");
            /*   Si un producto es elegido varias veces que muentre de 1 en 1 los productos
            asi cualquier cosa se elimina de la compra
            con el btn eliminar */

            while (Repetidor != unidades) {
                DefaultTableModel compras = (DefaultTableModel) TablaProductosCompra.getModel();

// Si el modelo no tiene columnas, las agregamos
                if (compras.getColumnCount() == 0) {
                    String titulos[] = {"CODIGO", "NOMBRE", "PRECIO", "ID"};
                    compras.setColumnIdentifiers(titulos);
                }

                int selectedRow = TablaProductos.getSelectedRow();
                if (selectedRow != -1) {
                    Double Price = (Double) TablaProductos.getValueAt(selectedRow, 3);
                    String Nombre = (String) TablaProductos.getValueAt(selectedRow, 1);
                    int Codigo = (int) TablaProductos.getValueAt(selectedRow, 0);
                    int ID = (int) TablaProductos.getValueAt(selectedRow, 5); // Asumiendo que el ID está en la última columna

                    Object[] objeto = {Codigo, Nombre, Price, ID}; // Asegúrate de que los índices coincidan con las columnas
                    compras.addRow(objeto);
                }

                int rowCount = compras.getRowCount();
                int columnCount = compras.getColumnCount();

// Recorrer todas las filas y columnas para extraer los datos 
                for (int i = 0; i < rowCount; i++) {
                    Object[] rowData = new Object[columnCount];
                    for (int j = 0; j < columnCount; j++) {
                        rowData[j] = compras.getValueAt(i, j);
                    }
                    datos.add(rowData);
                }

                Repetidor++;

                TablaProductosCompra.setModel(compras);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error");


    }//GEN-LAST:event_AgregarCompraActionPerformed
        Repetidor = 0;
        cargarTabla();
        ComprobarTextoDeBusqueda(busqueda);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        COMPRAS.setVisible(true);
        COMPRAS.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_unidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_unidadesMouseClicked
        txt_unidades.setText("");
    }//GEN-LAST:event_txt_unidadesMouseClicked

    private void txt_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unidadesActionPerformed

    }//GEN-LAST:event_txt_unidadesActionPerformed

    private void COMPRASWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_COMPRASWindowActivated
        /// CARGAR DATOS DE COMPRA
        BigDecimal redondear = new BigDecimal(PrecioFinal);
        redondear = redondear.setScale(2, RoundingMode.UP);

        jlb_productosA.setText(Count + " Productos");
        jbl_productosAPrice.setText("Precio Final: " + redondear);


    }//GEN-LAST:event_COMPRASWindowActivated

    private void TXT_PAGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_PAGOActionPerformed

    }//GEN-LAST:event_TXT_PAGOActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        /* Si el precio del producto $ es menor al pago que se ejecute
        sino no , sino daria errores por todos lados
         */
        try {

            //Comprobar si el jCheckBox esta activo sino que sea el pago manual
if(jcb_online.isSelected() == true){
                PagoFinal = PrecioFinal;
                } else {
    PagoFinal = Double.valueOf(TXT_PAGO.getText());
}
            if (jcb_online.isSelected()==true || PrecioFinal < PagoFinal ) {
                
                
                Imprimir IMPRESION = new Imprimir();
                IMPRESION.setVisible(true);
                IMPRESION.setLocationRelativeTo(this);
                COMPRAS.dispose();
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(rootPane, "EL IMPORTE ES MENOR AL PRECIO FINAL");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Porfavor ponga el importe");
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        COMPRAS.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_eliminarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarListActionPerformed

        //Metodo para elimninar de la tabla el producto seleccionado
        DefaultTableModel ComprasA = (DefaultTableModel) TablaProductosCompra.getModel();
        Double precioanterior = (Double) TablaProductosCompra.getValueAt(TablaProductosCompra.getSelectedRow(), 2);
        PrecioFinal = PrecioFinal - precioanterior;
        ComprasA.removeRow(TablaProductosCompra.getSelectedRow());
        BigDecimal redondear = new BigDecimal(PrecioFinal);
        redondear = redondear.setScale(2, RoundingMode.UP);
        Count--;
        jlb_productosA.setText(Count + " Productos");
        jbl_productosAPrice.setText("Precio Final: " + redondear);
        jlb_productosAgregados.setText("+ " + Count + " Precio Final: " + redondear);

        if (Count == 0) {
            redondear = BigDecimal.ZERO;
            jlb_productosA.setText("No hay Productos");
            jbl_productosAPrice.setText("Precio Final: " + redondear);
            jlb_productosAgregados.setText("Sin productos" + " Precio Final: " + redondear);

        }

    }//GEN-LAST:event_btn_eliminarListActionPerformed

    private void txt_Editar_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Editar_nombreActionPerformed
        TablaProductos.getSelectedRow();
    }//GEN-LAST:event_txt_Editar_nombreActionPerformed

    private void btn_Editar_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Editar_editarActionPerformed
//*********************************************************//
//Metodo para editar los productos , solo seleccionandolos //
//*********************************************************//
// Asegúrate de que los índices coincidan con las columnas //
//*********************************************************//
// Sino preparate para los errores                         //
//*********************************************************//
        try {
            Productos product = new Productos(identificador, txt_Editar_nombre.getText(), Integer.parseInt(txt_Editar_stock.getText()), Double.parseDouble(txt_Editar_precio.getText()),
                    txt_Editar_categoria.getText(), Integer.parseInt(txt_Editar_codigo.getText()));

            CL.Editar(product);
            JOptionPane.showMessageDialog(rootPane, "Se ha editado correctamente");
            cargarTabla();
            this.setEnabled(true);
            EDITAR.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error en los datos");

        }


    }//GEN-LAST:event_btn_Editar_editarActionPerformed

    private void btn_Editar_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Editar_cerrarActionPerformed
      
        /* Lo mismo que en agregar producto, el jframe principal
        se habilita cuando se cierra el editar */
        this.setEnabled(true);
        EDITAR.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Editar_cerrarActionPerformed

    private void EDITARWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_EDITARWindowOpened

       
    }//GEN-LAST:event_EDITARWindowOpened

    private void EDITARWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_EDITARWindowClosed

    }//GEN-LAST:event_EDITARWindowClosed

    private void jcb_onlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_onlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_onlineActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANEL_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANEL_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANEL_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANEL_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANEL_HOME().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCompra;
    public javax.swing.JFrame COMPRAS;
    private javax.swing.JFrame EDITAR;
    private javax.swing.JFrame REGISTRAR;
    private javax.swing.JTextField TXT_PAGO;
    private javax.swing.JTable TablaProductos;
    public static javax.swing.JTable TablaProductosCompra;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_Editar_cerrar;
    private javax.swing.JButton btn_Editar_editar;
    public javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_busqueda;
    private javax.swing.JButton btn_cambiar;
    private javax.swing.JButton btn_cerrar;
    public javax.swing.JButton btn_editar;
    protected javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminarList;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jbl_productosAPrice;
    private javax.swing.JLabel jbl_productosAPrice1;
    private javax.swing.JLabel jbl_productosAPrice2;
    private javax.swing.JCheckBox jcb_online;
    private javax.swing.JLabel jlb_Editar_categoria;
    private javax.swing.JLabel jlb_Editar_codigo;
    private javax.swing.JLabel jlb_Editar_nombre;
    private javax.swing.JLabel jlb_Editar_precio;
    private javax.swing.JLabel jlb_Editar_stock;
    private javax.swing.JLabel jlb_intruccion;
    private javax.swing.JLabel jlb_productosA;
    public static javax.swing.JLabel jlb_productosAgregados;
    private javax.swing.JLabel jlb_unidades;
    private javax.swing.JPanel jpanelEditar;
    private javax.swing.JLabel jtxt_bienvenido;
    private javax.swing.JLabel jtxt_user;
    private javax.swing.JTextField txt_Editar_categoria;
    private javax.swing.JTextField txt_Editar_codigo;
    private javax.swing.JTextField txt_Editar_nombre;
    private javax.swing.JTextField txt_Editar_precio;
    private javax.swing.JTextField txt_Editar_stock;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_producto;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_unidades;
    // End of variables declaration//GEN-END:variables

    
    
    // Metodo para recorrer la DB y cargarlo en la tabla
    public void cargarTabla() {
        DefaultTableModel model1 = new DefaultTableModel() {

            @Override
            //Filas y columnas no son editables
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        // nombres de columnas
        String titulos[] = {"CODIGO", "NOMBRE", "STOCK", "PRECIO", "CATEGORIA", "ID"};

        //Setear nombres en coolumnas
        model1.setColumnIdentifiers(titulos);

        //carga de datos en la db
        List<Productos> listaproductos = CL.cargarTabla();

        //recorrer la lista y mostrar elementos
        if (listaproductos != null) {

            for (Productos product : listaproductos) {
                Object[] objeto = {product.getCodigo(), product.getNombre(),
                    product.getStock(), product.getPrecio(), product.getCategoria(), product.getId()};

//agregar listas 
                model1.addRow(objeto);
            }

        }
        TablaProductos.setModel(model1);
    }

    private void CargarCompras() {
        DefaultTableModel compras = new DefaultTableModel() {
        };

// nombres de columnas
        String titulos[] = {"CODIGO", "NOMBRE", "STOCK", "PRECIO", "CATEGORIA", "ID"};
        compras.setColumnIdentifiers(titulos);

        int selectedRow = TablaProductos.getSelectedRow();
        if (selectedRow != -1) {
            Double Precio = (Double) TablaProductos.getValueAt(selectedRow, 3);
            String Nombre = (String) TablaProductos.getValueAt(selectedRow, 1);
            int Codigo = (int) TablaProductos.getValueAt(selectedRow, 0);
            int ID = (int) TablaProductos.getValueAt(selectedRow, 5); // Asumiendo que el ID está en la última columna

            Object[] objeto = {Codigo, Nombre, null, Precio, null, ID}; // Asegúrate de que los índices coincidan con las columnas
            compras.addRow(objeto);
        }

        TablaProductosCompra.setModel(compras);

    }

    public void CambiarTextoDeBusqueda() {
        if (busqueda == false) {

            TextoCode();
            btn_cambiar.setText("CAMBIAR A BUSQUEDA POR NOMBRE");
            busqueda = true;
        } else {

            TextoName();
            btn_cambiar.setText("CAMBIAR A BUSQUEDA POR CODIGO");

            busqueda = false;
        }

    }

    //Cambiar texto a codigo del producto como guia
    public void TextoCode() {
        txt_producto.setText("EJEMPLO: 08721456");
        txt_producto.setForeground(Color.GRAY);
        producto_busqueda = "";
        jlb_intruccion.setText("Introduce el codigo del producto");

    }
// Cambiar texto a nombre del producto como guia
    public void TextoName() {
        txt_producto.setText("EJEMPLO: Ryzen 5");
        txt_producto.setForeground(Color.GRAY);
        jlb_intruccion.setText("Introduce el nombre del producto");
        producto_busqueda = "";

    }
/* Comprueba si el boolean busqueda es verdadero o falso
    y ejecuta los metodos de arriba */
    public void ComprobarTextoDeBusqueda(boolean busquedas) {
        if (busquedas == false) {

            TextoName();

        } else {
            TextoCode();

        }

    }

    
    //Limpia el registro asi queda como nuevo
    public void LimpiarRegistrarP() {

        txt_nombre.setText("");
        txt_precio.setText("");
        txt_categoria.setText("");
        txt_stock.setText("");
        txt_codigo.setText("");

    }

    //Carga los datos que se van a usar en los txt_field en Editar
    public void CargarEditar() {
        TablaProductos.getSelectedRow();

        Double Price = (Double) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 3);
        String Nombre = (String) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 1);
        int Codigo = (int) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 0);
        identificador = (int) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 5); // Asumiendo que el ID está en la última columna
        int Stock = (int) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 2);
        String Categoria = (String) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 4);
        txt_Editar_stock.setText(Integer.toString(Stock));
        txt_Editar_codigo.setText(Integer.toString(Codigo));
        txt_Editar_nombre.setText(Nombre);
        txt_Editar_precio.setText(Price.toString());
        txt_Editar_categoria.setText(Categoria);

    }

}
